# Generated by Django 3.0.6 on 2020-05-22 06:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('M', 'Manager'), ('E', 'Employee')], max_length=1)),
                ('contact', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter in format +9999999999. Upto 10 digits allowed', regex='^\\+?1?\\d{10,10}$')])),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('dept', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personalnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Content', models.TextField(max_length=700)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(default=None, max_length=30)),
                ('Subject', models.CharField(max_length=100)),
                ('Content', models.TextField(max_length=700)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('days_asked', models.PositiveIntegerField(default=2)),
                ('days_approved', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(max_length=2000)),
                ('dept', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Application',
                'verbose_name_plural': 'Leave Applications',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.DateTimeField()),
                ('Work_Day', models.IntegerField()),
                ('Leave', models.IntegerField()),
                ('Dayoff', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
